// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://wnkkoimvxioevzvrzzru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indua2tvaW12eGlvZXZ6dnJ6enJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2NTY4MzUsImV4cCI6MjA3NTIzMjgzNX0.aho27vu2yQ8Kt9tVFF-IwnUnpyCe5DbvVStAv9cv6YQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
